# Generated by Django 5.1.2 on 2024-10-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_thread_thread_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='thread',
        ),
        migrations.AddField(
            model_name='chat',
            name='thread_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
