# Generated by Django 5.1.2 on 2024-11-05 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_chat_thread_chat_thread_id_delete_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_uploaded', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_vault', to='bot.chat')),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=50, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('bytes', models.BigIntegerField()),
                ('purpose', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('object_type', models.CharField(default='upload', max_length=50)),
                ('file_vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bot.filevault')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_id'], name='bot_fileinf_file_id_8550d7_idx'), models.Index(fields=['purpose'], name='bot_fileinf_purpose_044518_idx'), models.Index(fields=['status'], name='bot_fileinf_status_612394_idx')],
            },
        ),
    ]
