# Generated by Django 5.1.2 on 2024-11-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_filevault_fileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='dimensions',
            field=models.IntegerField(default=1536),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='embedding_format',
            field=models.CharField(choices=[('base64', 'Base64'), ('float', 'Float')], default='float', max_length=20),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='fileinfo',
            index=models.Index(fields=['embedding_format'], name='bot_fileinf_embeddi_d22a54_idx'),
        ),
    ]
