# Generated by Django 5.1.2 on 2024-11-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_batch_batchrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrequest',
            name='assistant_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
