# Generated by Django 5.1.2 on 2024-11-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_batchrequest_assistant_message_alter_batch_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
