# Generated by Django 5.1.2 on 2024-11-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_fileinfo_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filevault',
            name='chat',
        ),
    ]
